//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLREdit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BLREdit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Client.
        /// </summary>
        public static string btn_AddClient {
            get {
                return ResourceManager.GetString("btn_AddClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Loadout.
        /// </summary>
        public static string btn_AddProfile {
            get {
                return ResourceManager.GetString("btn_AddProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Server.
        /// </summary>
        public static string btn_AddServer {
            get {
                return ResourceManager.GetString("btn_AddServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        public static string btn_Ascending {
            get {
                return ResourceManager.GetString("btn_Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string btn_ConnectToServer {
            get {
                return ResourceManager.GetString("btn_ConnectToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Client.
        /// </summary>
        public static string btn_DefaultClient {
            get {
                return ResourceManager.GetString("btn_DefaultClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        public static string btn_Descending {
            get {
                return ResourceManager.GetString("btn_Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string btn_DuplicateCurrentProfile {
            get {
                return ResourceManager.GetString("btn_DuplicateCurrentProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Loadouts.
        /// </summary>
        public static string btn_ExportProfile {
            get {
                return ResourceManager.GetString("btn_ExportProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string btn_GenderToggle_Female {
            get {
                return ResourceManager.GetString("btn_GenderToggle_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string btn_GenderToggle_Male {
            get {
                return ResourceManager.GetString("btn_GenderToggle_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Match.
        /// </summary>
        public static string btn_QuickMatch {
            get {
                return ResourceManager.GetString("btn_QuickMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize.
        /// </summary>
        public static string btn_RandomizeLoadout {
            get {
                return ResourceManager.GetString("btn_RandomizeLoadout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Server.
        /// </summary>
        public static string btn_RemoveServer {
            get {
                return ResourceManager.GetString("btn_RemoveServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert To Default.
        /// </summary>
        public static string btn_ResetToDefaults {
            get {
                return ResourceManager.GetString("btn_ResetToDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Bot Match.
        /// </summary>
        public static string btn_StartBotMatch {
            get {
                return ResourceManager.GetString("btn_StartBotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Server.
        /// </summary>
        public static string btn_StartServer {
            get {
                return ResourceManager.GetString("btn_StartServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Training.
        /// </summary>
        public static string btn_StartTraining {
            get {
                return ResourceManager.GetString("btn_StartTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify the Blacklight:Retribution Game Client.
        /// </summary>
        public static string btn_TT_ConfigureClient {
            get {
                return ResourceManager.GetString("btn_TT_ConfigureClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to Server.
        /// </summary>
        public static string btn_TT_ConnectToServer {
            get {
                return ResourceManager.GetString("btn_TT_ConnectToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Server Configuration.
        /// </summary>
        public static string btn_TT_OpenServerConfigWindow {
            get {
                return ResourceManager.GetString("btn_TT_OpenServerConfigWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping Server.
        /// </summary>
        public static string btn_TT_PingServer {
            get {
                return ResourceManager.GetString("btn_TT_PingServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resets BLREdit Config(Settings, ServerList, ClientList), but will keep your loadouts, in-game settings, backups and log files..
        /// </summary>
        public static string btn_TT_ResetToDefaults {
            get {
                return ResourceManager.GetString("btn_TT_ResetToDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accuracy.
        /// </summary>
        public static string enum_Accuracy {
            get {
                return ResourceManager.GetString("enum_Accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aim.
        /// </summary>
        public static string enum_Aim {
            get {
                return ResourceManager.GetString("enum_Aim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ammo.
        /// </summary>
        public static string enum_Ammo {
            get {
                return ResourceManager.GetString("enum_Ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character.
        /// </summary>
        public static string enum_Character {
            get {
                return ResourceManager.GetString("enum_Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CP.
        /// </summary>
        public static string enum_CP {
            get {
                return ResourceManager.GetString("enum_CP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        public static string enum_Damage {
            get {
                return ResourceManager.GetString("enum_Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electro Prot.
        /// </summary>
        public static string enum_ElectroProtection {
            get {
                return ResourceManager.GetString("enum_ElectroProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explosive Prot.
        /// </summary>
        public static string enum_ExplosiveProtection {
            get {
                return ResourceManager.GetString("enum_ExplosiveProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear Slots.
        /// </summary>
        public static string enum_GearSlots {
            get {
                return ResourceManager.GetString("enum_GearSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head Prot.
        /// </summary>
        public static string enum_HeadProtection {
            get {
                return ResourceManager.GetString("enum_HeadProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        public static string enum_Health {
            get {
                return ResourceManager.GetString("enum_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hip.
        /// </summary>
        public static string enum_Hip {
            get {
                return ResourceManager.GetString("enum_Hip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HRV Duration.
        /// </summary>
        public static string enum_HRVDuration {
            get {
                return ResourceManager.GetString("enum_HRVDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HRV Recharge.
        /// </summary>
        public static string enum_HRVRecharge {
            get {
                return ResourceManager.GetString("enum_HRVRecharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incendiary Prot.
        /// </summary>
        public static string enum_IncendiaryProtection {
            get {
                return ResourceManager.GetString("enum_IncendiaryProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrared.
        /// </summary>
        public static string enum_Infrared {
            get {
                return ResourceManager.GetString("enum_Infrared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrared Prot.
        /// </summary>
        public static string enum_InfraredProtection {
            get {
                return ResourceManager.GetString("enum_InfraredProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last  Applied.
        /// </summary>
        public static string enum_LastApplied {
            get {
                return ResourceManager.GetString("enum_LastApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified.
        /// </summary>
        public static string enum_LastModified {
            get {
                return ResourceManager.GetString("enum_LastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Viewed.
        /// </summary>
        public static string enum_LastViewed {
            get {
                return ResourceManager.GetString("enum_LastViewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melee Prot.
        /// </summary>
        public static string enum_MeleeProtection {
            get {
                return ResourceManager.GetString("enum_MeleeProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string enum_Move {
            get {
                return ResourceManager.GetString("enum_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string enum_Name {
            get {
                return ResourceManager.GetString("enum_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string enum_None {
            get {
                return ResourceManager.GetString("enum_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        public static string enum_Range {
            get {
                return ResourceManager.GetString("enum_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recoil.
        /// </summary>
        public static string enum_Recoil {
            get {
                return ResourceManager.GetString("enum_Recoil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string enum_Reload {
            get {
                return ResourceManager.GetString("enum_Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string enum_Run {
            get {
                return ResourceManager.GetString("enum_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScopeInTime.
        /// </summary>
        public static string enum_ScopeInTime {
            get {
                return ResourceManager.GetString("enum_ScopeInTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time of Creation.
        /// </summary>
        public static string enum_TimeOfCreation {
            get {
                return ResourceManager.GetString("enum_TimeOfCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toxic Prot.
        /// </summary>
        public static string enum_ToxicProtection {
            get {
                return ResourceManager.GetString("enum_ToxicProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        public static string enum_Zoom {
            get {
                return ResourceManager.GetString("enum_Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This profile has Advanced Modding enabled.
        /// </summary>
        public static string img_TT_AdvancedInfo {
            get {
                return ResourceManager.GetString("img_TT_AdvancedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item might not work properly on this weapon.
        /// </summary>
        public static string img_TT_AdvancedModeWarning {
            get {
                return ResourceManager.GetString("img_TT_AdvancedModeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accuracy:.
        /// </summary>
        public static string lbl_Accuracy {
            get {
                return ResourceManager.GetString("lbl_Accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ammo:.
        /// </summary>
        public static string lbl_Ammo {
            get {
                return ResourceManager.GetString("lbl_Ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor &amp; Gear:.
        /// </summary>
        public static string lbl_ArmorAndGear {
            get {
                return ResourceManager.GetString("lbl_ArmorAndGear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run:.
        /// </summary>
        public static string lbl_ArmorRun {
            get {
                return ResourceManager.GetString("lbl_ArmorRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BotCount:.
        /// </summary>
        public static string lbl_BotCount {
            get {
                return ResourceManager.GetString("lbl_BotCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat:.
        /// </summary>
        public static string lbl_ChatKeyBind {
            get {
                return ResourceManager.GetString("lbl_ChatKeyBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CP:.
        /// </summary>
        public static string lbl_CP {
            get {
                return ResourceManager.GetString("lbl_CP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Mod Percentages:.
        /// </summary>
        public static string lbl_CurrentModPercentages {
            get {
                return ResourceManager.GetString("lbl_CurrentModPercentages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage:.
        /// </summary>
        public static string lbl_Damage {
            get {
                return ResourceManager.GetString("lbl_Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depot:.
        /// </summary>
        public static string lbl_Depot {
            get {
                return ResourceManager.GetString("lbl_Depot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electro Prot:.
        /// </summary>
        public static string lbl_ElectroProtection {
            get {
                return ResourceManager.GetString("lbl_ElectroProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explosive Prot:.
        /// </summary>
        public static string lbl_ExplosiveProtection {
            get {
                return ResourceManager.GetString("lbl_ExplosiveProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire:.
        /// </summary>
        public static string lbl_FireKeyBind {
            get {
                return ResourceManager.GetString("lbl_FireKeyBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fragments Per Shell:.
        /// </summary>
        public static string lbl_FragmentsPerShell {
            get {
                return ResourceManager.GetString("lbl_FragmentsPerShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear Slots:.
        /// </summary>
        public static string lbl_GearSlots {
            get {
                return ResourceManager.GetString("lbl_GearSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head Prot:.
        /// </summary>
        public static string lbl_HeadArmor {
            get {
                return ResourceManager.GetString("lbl_HeadArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health:.
        /// </summary>
        public static string lbl_Health {
            get {
                return ResourceManager.GetString("lbl_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crouch:.
        /// </summary>
        public static string lbl_HoldCrouchKeyBind {
            get {
                return ResourceManager.GetString("lbl_HoldCrouchKeyBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HRV:.
        /// </summary>
        public static string lbl_HRVDuration {
            get {
                return ResourceManager.GetString("lbl_HRVDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recharge:.
        /// </summary>
        public static string lbl_HRVRecharge {
            get {
                return ResourceManager.GetString("lbl_HRVRecharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incendiary Prot:.
        /// </summary>
        public static string lbl_IncendiaryProtection {
            get {
                return ResourceManager.GetString("lbl_IncendiaryProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrared:.
        /// </summary>
        public static string lbl_Infrared {
            get {
                return ResourceManager.GetString("lbl_Infrared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrared Prot:.
        /// </summary>
        public static string lbl_InfraredProtection {
            get {
                return ResourceManager.GetString("lbl_InfraredProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump:.
        /// </summary>
        public static string lbl_JumpKeyBind {
            get {
                return ResourceManager.GetString("lbl_JumpKeyBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string lbl_Language {
            get {
                return ResourceManager.GetString("lbl_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Weapon:.
        /// </summary>
        public static string lbl_LastWeaponKeyBind {
            get {
                return ResourceManager.GetString("lbl_LastWeaponKeyBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melee:.
        /// </summary>
        public static string lbl_MeleeKeyBind {
            get {
                return ResourceManager.GetString("lbl_MeleeKeyBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melee Prot:.
        /// </summary>
        public static string lbl_MeleeProtection {
            get {
                return ResourceManager.GetString("lbl_MeleeProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Backward:.
        /// </summary>
        public static string lbl_MoveBackwardKeyBind {
            get {
                return ResourceManager.GetString("lbl_MoveBackwardKeyBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Forward:.
        /// </summary>
        public static string lbl_MoveForwardKeyBind {
            get {
                return ResourceManager.GetString("lbl_MoveForwardKeyBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Weapon:.
        /// </summary>
        public static string lbl_NextWeaponKeyBind {
            get {
                return ResourceManager.GetString("lbl_NextWeaponKeyBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run:.
        /// </summary>
        public static string lbl_PawnRun {
            get {
                return ResourceManager.GetString("lbl_PawnRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickup Weapon:.
        /// </summary>
        public static string lbl_PickupWeaponKeyBind {
            get {
                return ResourceManager.GetString("lbl_PickupWeaponKeyBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlayerCount:.
        /// </summary>
        public static string lbl_PlayerCount {
            get {
                return ResourceManager.GetString("lbl_PlayerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Name:.
        /// </summary>
        public static string lbl_PlayerName {
            get {
                return ResourceManager.GetString("lbl_PlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Weapon:.
        /// </summary>
        public static string lbl_PrevWeaponKeyBind {
            get {
                return ResourceManager.GetString("lbl_PrevWeaponKeyBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary.
        /// </summary>
        public static string lbl_Primary {
            get {
                return ResourceManager.GetString("lbl_Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Gear:.
        /// </summary>
        public static string lbl_QuickGearKeyBind {
            get {
                return ResourceManager.GetString("lbl_QuickGearKeyBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range:.
        /// </summary>
        public static string lbl_Range {
            get {
                return ResourceManager.GetString("lbl_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firerate:.
        /// </summary>
        public static string lbl_RateOfFire {
            get {
                return ResourceManager.GetString("lbl_RateOfFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recoil:.
        /// </summary>
        public static string lbl_Recoil {
            get {
                return ResourceManager.GetString("lbl_Recoil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recoil Accumulation:.
        /// </summary>
        public static string lbl_RecoilAccumulation {
            get {
                return ResourceManager.GetString("lbl_RecoilAccumulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recoil Aim:.
        /// </summary>
        public static string lbl_RecoilAim {
            get {
                return ResourceManager.GetString("lbl_RecoilAim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recoil:.
        /// </summary>
        public static string lbl_RecoilHip {
            get {
                return ResourceManager.GetString("lbl_RecoilHip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recoil Recovery:.
        /// </summary>
        public static string lbl_RecoilRecoveryTime {
            get {
                return ResourceManager.GetString("lbl_RecoilRecoveryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Recoil Ratio:.
        /// </summary>
        public static string lbl_RecoilVerticalRatio {
            get {
                return ResourceManager.GetString("lbl_RecoilVerticalRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region:.
        /// </summary>
        public static string lbl_Region {
            get {
                return ResourceManager.GetString("lbl_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload:.
        /// </summary>
        public static string lbl_ReloadEmpty {
            get {
                return ResourceManager.GetString("lbl_ReloadEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload:.
        /// </summary>
        public static string lbl_ReloadKeyBind {
            get {
                return ResourceManager.GetString("lbl_ReloadKeyBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload:.
        /// </summary>
        public static string lbl_ReloadPartial {
            get {
                return ResourceManager.GetString("lbl_ReloadPartial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed:.
        /// </summary>
        public static string lbl_Run {
            get {
                return ResourceManager.GetString("lbl_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScopeIn:.
        /// </summary>
        public static string lbl_ScopeInTime {
            get {
                return ResourceManager.GetString("lbl_ScopeInTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary:.
        /// </summary>
        public static string lbl_Secondary {
            get {
                return ResourceManager.GetString("lbl_Secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLREdit Build:.
        /// </summary>
        public static string lbl_SelectedBLREditVersion {
            get {
                return ResourceManager.GetString("lbl_SelectedBLREditVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLRevive Build:.
        /// </summary>
        public static string lbl_SelectedBLReviveVersion {
            get {
                return ResourceManager.GetString("lbl_SelectedBLReviveVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProxyVersion:.
        /// </summary>
        public static string lbl_SelectedProxyVersion {
            get {
                return ResourceManager.GetString("lbl_SelectedProxyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equip Primary:.
        /// </summary>
        public static string lbl_SelectPrimaryWeaponKeyBind {
            get {
                return ResourceManager.GetString("lbl_SelectPrimaryWeaponKeyBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equip Secondary:.
        /// </summary>
        public static string lbl_SelectSecondaryWeaponKeyBind {
            get {
                return ResourceManager.GetString("lbl_SelectSecondaryWeaponKeyBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equip Tacitcal:.
        /// </summary>
        public static string lbl_SelectTacticalKeyBind {
            get {
                return ResourceManager.GetString("lbl_SelectTacticalKeyBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerAddress:.
        /// </summary>
        public static string lbl_ServerAddress {
            get {
                return ResourceManager.GetString("lbl_ServerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info Port:.
        /// </summary>
        public static string lbl_ServerInfoPort {
            get {
                return ResourceManager.GetString("lbl_ServerInfoPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        public static string lbl_ServerPort {
            get {
                return ResourceManager.GetString("lbl_ServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aim:.
        /// </summary>
        public static string lbl_SpreadAim {
            get {
                return ResourceManager.GetString("lbl_SpreadAim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spread Center:.
        /// </summary>
        public static string lbl_SpreadCenter {
            get {
                return ResourceManager.GetString("lbl_SpreadCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spread Center Weight:.
        /// </summary>
        public static string lbl_SpreadCenterWeight {
            get {
                return ResourceManager.GetString("lbl_SpreadCenterWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crouch Spread Multiplier:.
        /// </summary>
        public static string lbl_SpreadCrouchMultiplier {
            get {
                return ResourceManager.GetString("lbl_SpreadCrouchMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hip:.
        /// </summary>
        public static string lbl_SpreadHipfire {
            get {
                return ResourceManager.GetString("lbl_SpreadHipfire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump Spread Multiplier:.
        /// </summary>
        public static string lbl_SpreadJumpMultiplier {
            get {
                return ResourceManager.GetString("lbl_SpreadJumpMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move:.
        /// </summary>
        public static string lbl_SpreadMove {
            get {
                return ResourceManager.GetString("lbl_SpreadMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprint:.
        /// </summary>
        public static string lbl_SprintKeyBind {
            get {
                return ResourceManager.GetString("lbl_SprintKeyBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Left:.
        /// </summary>
        public static string lbl_StrafeLeftKeyBind {
            get {
                return ResourceManager.GetString("lbl_StrafeLeftKeyBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Right:.
        /// </summary>
        public static string lbl_StrafeRightKeyBind {
            get {
                return ResourceManager.GetString("lbl_StrafeRightKeyBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equip Gear 1:.
        /// </summary>
        public static string lbl_SwitchGear1KeyBind {
            get {
                return ResourceManager.GetString("lbl_SwitchGear1KeyBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equip Gear 2:.
        /// </summary>
        public static string lbl_SwitchGear2KeyBind {
            get {
                return ResourceManager.GetString("lbl_SwitchGear2KeyBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equip Gear 3:.
        /// </summary>
        public static string lbl_SwitchGear3KeyBind {
            get {
                return ResourceManager.GetString("lbl_SwitchGear3KeyBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equip Gear 4:.
        /// </summary>
        public static string lbl_SwitchGear4KeyBind {
            get {
                return ResourceManager.GetString("lbl_SwitchGear4KeyBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taunts:.
        /// </summary>
        public static string lbl_Taunt {
            get {
                return ResourceManager.GetString("lbl_Taunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taunt:.
        /// </summary>
        public static string lbl_TauntKeyBind {
            get {
                return ResourceManager.GetString("lbl_TauntKeyBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HRV:.
        /// </summary>
        public static string lbl_ToggleVisorKeyBind {
            get {
                return ResourceManager.GetString("lbl_ToggleVisorKeyBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom:.
        /// </summary>
        public static string lbl_ToggleZoomKeyBind {
            get {
                return ResourceManager.GetString("lbl_ToggleZoomKeyBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toxic Prot:.
        /// </summary>
        public static string lbl_ToxicProtection {
            get {
                return ResourceManager.GetString("lbl_ToxicProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Object:.
        /// </summary>
        public static string lbl_UseObjectKeyBind {
            get {
                return ResourceManager.GetString("lbl_UseObjectKeyBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom:.
        /// </summary>
        public static string lbl_Zoom {
            get {
                return ResourceManager.GetString("lbl_Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoomfirerate:.
        /// </summary>
        public static string lbl_ZoomFirerate {
            get {
                return ResourceManager.GetString("lbl_ZoomFirerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdvancedModding:.
        /// </summary>
        public static string msg_AdvancedModding {
            get {
                return ResourceManager.GetString("msg_AdvancedModding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please change your player name!.
        /// </summary>
        public static string msg_ChangePlayerName {
            get {
                return ResourceManager.GetString("msg_ChangePlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed to start server:\n{0}.
        /// </summary>
        public static string msg_FailedToStartServer {
            get {
                return ResourceManager.GetString("msg_FailedToStartServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLREdit will now Download Missing Files!.
        /// </summary>
        public static string msg_MisingFiles {
            get {
                return ResourceManager.GetString("msg_MisingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Packaging folder?.
        /// </summary>
        public static string msg_OpenPackagingFolder {
            get {
                return ResourceManager.GetString("msg_OpenPackagingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed to package release:\n{0}.
        /// </summary>
        public static string msg_PackagingFailed {
            get {
                return ResourceManager.GetString("msg_PackagingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to return to Default Config?.
        /// </summary>
        public static string msg_ResetConfig {
            get {
                return ResourceManager.GetString("msg_ResetConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now Returning to Defaults. this will also restart BLREdit!.
        /// </summary>
        public static string msg_ResetConfigInfo {
            get {
                return ResourceManager.GetString("msg_ResetConfigInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLREdit will now Update!.
        /// </summary>
        public static string msg_Update {
            get {
                return ResourceManager.GetString("msg_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLREdit will now Download Missing Files and Update!.
        /// </summary>
        public static string msg_UpdateMissingFiles {
            get {
                return ResourceManager.GetString("msg_UpdateMissingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed reading {0}, found Folders:{1}, steam library parsing aborted reason:\n{2}.
        /// </summary>
        public static string msg_VDFGamePathError {
            get {
                return ResourceManager.GetString("msg_VDFGamePathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLREdit encountered an Error!.
        /// </summary>
        public static string msgT_Error {
            get {
                return ResourceManager.GetString("msgT_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice!.
        /// </summary>
        public static string msgT_Info {
            get {
                return ResourceManager.GetString("msgT_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset BLRedit Config.
        /// </summary>
        public static string msgT_ResetConfig {
            get {
                return ResourceManager.GetString("msgT_ResetConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdvancedModding.
        /// </summary>
        public static string tbtn_AdvancedModding {
            get {
                return ResourceManager.GetString("tbtn_AdvancedModding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomModules.
        /// </summary>
        public static string tbtn_AllowCustomModules {
            get {
                return ResourceManager.GetString("tbtn_AllowCustomModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debugging.
        /// </summary>
        public static string tbtn_Debugging {
            get {
                return ResourceManager.GetString("tbtn_Debugging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable BLREdit API.
        /// </summary>
        public static string tbtn_EnableAPI {
            get {
                return ResourceManager.GetString("tbtn_EnableAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framerate Smoothing.
        /// </summary>
        public static string tbtn_EnableFramerateSmoothing {
            get {
                return ResourceManager.GetString("tbtn_EnableFramerateSmoothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForceRuntimeCheck.
        /// </summary>
        public static string tbtn_ForceRuntimeCheck {
            get {
                return ResourceManager.GetString("tbtn_ForceRuntimeCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framerate Smoothing VSync.
        /// </summary>
        public static string tbtn_FramerateSmoothingVSync {
            get {
                return ResourceManager.GetString("tbtn_FramerateSmoothingVSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Required Modules.
        /// </summary>
        public static string tbtn_InstallRequiredModules {
            get {
                return ResourceManager.GetString("tbtn_InstallRequiredModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping Hidden Servers.
        /// </summary>
        public static string tbtn_PingHiddenServers {
            get {
                return ResourceManager.GetString("tbtn_PingHiddenServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RuntimeCheck.
        /// </summary>
        public static string tbtn_RuntimeCheck {
            get {
                return ResourceManager.GetString("tbtn_RuntimeCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server WatchDog.
        /// </summary>
        public static string tbtn_ServerWatchDog {
            get {
                return ResourceManager.GetString("tbtn_ServerWatchDog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Hidden Servers.
        /// </summary>
        public static string tbtn_ShowHiddenServers {
            get {
                return ResourceManager.GetString("tbtn_ShowHiddenServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateNotice.
        /// </summary>
        public static string tbtn_ShowUpdateNotice {
            get {
                return ResourceManager.GetString("tbtn_ShowUpdateNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StrictModuleChecks.
        /// </summary>
        public static string tbtn_StrictModuleChecks {
            get {
                return ResourceManager.GetString("tbtn_StrictModuleChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows for Weapon Builds which are normaly not possible.
        /// </summary>
        public static string tbtn_TT_AdvancedModding {
            get {
                return ResourceManager.GetString("tbtn_TT_AdvancedModding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows BLREdit to Adopt Modules in the Module Folder into the Installed Module List Client and Server are both set as Default to be Loaded.
        /// </summary>
        public static string tbtn_TT_AllowCustomModules {
            get {
                return ResourceManager.GetString("tbtn_TT_AllowCustomModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doesn&apos;t have any effect currently.
        /// </summary>
        public static string tbtn_TT_Debugging {
            get {
                return ResourceManager.GetString("tbtn_TT_Debugging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables the App-Web-Protocol API.
        ///Important needs Admin priviliges to install the Protocol into the Windows Registry. 
        ///Needs a Restart to Install Protocol!.
        /// </summary>
        public static string tbtn_TT_EnableAPI {
            get {
                return ResourceManager.GetString("tbtn_TT_EnableAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables Framerate Smoothing and removes the framerate cap.
        /// </summary>
        public static string tbtn_TT_EnableFramerateSmoothing {
            get {
                return ResourceManager.GetString("tbtn_TT_EnableFramerateSmoothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forces the Runtime Check Dialog to display.
        /// </summary>
        public static string tbtn_TT_ForceRuntimeCheck {
            get {
                return ResourceManager.GetString("tbtn_TT_ForceRuntimeCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the Framerate cap to the Display Refreshrate.
        /// </summary>
        public static string tbtn_TT_FramerateSmoothingVSync {
            get {
                return ResourceManager.GetString("tbtn_TT_FramerateSmoothingVSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installs all Required Modules just before launch.
        /// </summary>
        public static string tbtn_TT_InstallRequiredModules {
            get {
                return ResourceManager.GetString("tbtn_TT_InstallRequiredModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping Hidden Servers and Show them if online..
        /// </summary>
        public static string tbtn_TT_PingHiddenServers {
            get {
                return ResourceManager.GetString("tbtn_TT_PingHiddenServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks if all necessary MVC++ Runtimes are installed to make the Gamework only needed when the game was not installed via Steam.
        /// </summary>
        public static string tbtn_TT_RuntimeCheck {
            get {
                return ResourceManager.GetString("tbtn_TT_RuntimeCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables the Server WatchDog which will Restart&apos;s the server instantly if it crashes or get&apos;s closed while BLRedit is Runnning!.
        /// </summary>
        public static string tbtn_TT_ServerWatchDog {
            get {
                return ResourceManager.GetString("tbtn_TT_ServerWatchDog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Hidden Servers even when they are offline.
        /// </summary>
        public static string tbtn_TT_ShowHiddenServers {
            get {
                return ResourceManager.GetString("tbtn_TT_ShowHiddenServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the default Web browser to the Newest release when a new one is available.
        /// </summary>
        public static string tbtn_TT_ShowUpdateNotice {
            get {
                return ResourceManager.GetString("tbtn_TT_ShowUpdateNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Allows Proxy Modules from the GitHub List.
        /// </summary>
        public static string tbtn_TT_StrictModuleChecks {
            get {
                return ResourceManager.GetString("tbtn_TT_StrictModuleChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patches.
        /// </summary>
        public static string ti_ClientPatchList {
            get {
                return ResourceManager.GetString("ti_ClientPatchList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed Info.
        /// </summary>
        public static string ti_DetailedInfo {
            get {
                return ResourceManager.GetString("ti_DetailedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra.
        /// </summary>
        public static string ti_Extra {
            get {
                return ResourceManager.GetString("ti_Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear.
        /// </summary>
        public static string ti_Gear {
            get {
                return ResourceManager.GetString("ti_Gear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item List.
        /// </summary>
        public static string ti_ItemList {
            get {
                return ResourceManager.GetString("ti_ItemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher.
        /// </summary>
        public static string ti_Launcher {
            get {
                return ResourceManager.GetString("ti_Launcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loadout 1.
        /// </summary>
        public static string ti_Loadout1 {
            get {
                return ResourceManager.GetString("ti_Loadout1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loadout 2.
        /// </summary>
        public static string ti_Loadout2 {
            get {
                return ResourceManager.GetString("ti_Loadout2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loadout 3.
        /// </summary>
        public static string ti_Loadout3 {
            get {
                return ResourceManager.GetString("ti_Loadout3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        public static string ti_ProxyModuleList {
            get {
                return ResourceManager.GetString("ti_ProxyModuleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ti_Settings {
            get {
                return ResourceManager.GetString("ti_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapons.
        /// </summary>
        public static string ti_Weapons {
            get {
                return ResourceManager.GetString("ti_Weapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlayerName can only contain: [a-z], [A-Z], [0-9], dash( - ), underscore( _ ) and dot( . )..
        /// </summary>
        public static string txt_TT_PlayerName {
            get {
                return ResourceManager.GetString("txt_TT_PlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region examples (EU-West, US-West, AU, OCE, LATAM).
        /// </summary>
        public static string txt_TT_Region {
            get {
                return ResourceManager.GetString("txt_TT_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can select which version of BLREdit you want to use..
        /// </summary>
        public static string txt_TT_SelectedBLREditVersion {
            get {
                return ResourceManager.GetString("txt_TT_SelectedBLREditVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can select which version of BLRevive you want to use..
        /// </summary>
        public static string txt_TT_SelectedBLReviveVersion {
            get {
                return ResourceManager.GetString("txt_TT_SelectedBLReviveVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available ProxyVersions: v1.0.0-beta.2, v1.0.0-beta.3
        ///Info:
        ///beta3 will only start in windowed mode but you can ALT+Enter to go to fullscreen
        ///and might also be still very buggy.
        /// </summary>
        public static string txt_TT_SelectedProxyVersion {
            get {
                return ResourceManager.GetString("txt_TT_SelectedProxyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Configuration.
        /// </summary>
        public static string winT_ClientConfigWindow {
            get {
                return ResourceManager.GetString("winT_ClientConfigWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Progress Info.
        /// </summary>
        public static string winT_DownloadInfoWindow {
            get {
                return ResourceManager.GetString("winT_DownloadInfoWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Missing Runtimes!.
        /// </summary>
        public static string winT_DownloadMissingRuntimes {
            get {
                return ResourceManager.GetString("winT_DownloadMissingRuntimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map &amp; Mode Selection.
        /// </summary>
        public static string winT_MapAndModeSelect {
            get {
                return ResourceManager.GetString("winT_MapAndModeSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Configuration.
        /// </summary>
        public static string winT_ServerConfigWindow {
            get {
                return ResourceManager.GetString("winT_ServerConfigWindow", resourceCulture);
            }
        }
    }
}
