//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLREdit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BLREdit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Client.
        /// </summary>
        public static string btn_AddClient {
            get {
                return ResourceManager.GetString("btn_AddClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Profile.
        /// </summary>
        public static string btn_AddProfile {
            get {
                return ResourceManager.GetString("btn_AddProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Server.
        /// </summary>
        public static string btn_AddServer {
            get {
                return ResourceManager.GetString("btn_AddServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string btn_DuplicateCurrentProfile {
            get {
                return ResourceManager.GetString("btn_DuplicateCurrentProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Profile.
        /// </summary>
        public static string btn_ExportProfile {
            get {
                return ResourceManager.GetString("btn_ExportProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string btn_GenderToggle_Female {
            get {
                return ResourceManager.GetString("btn_GenderToggle_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string btn_GenderToggle_Male {
            get {
                return ResourceManager.GetString("btn_GenderToggle_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize.
        /// </summary>
        public static string btn_RandomizeLoadout {
            get {
                return ResourceManager.GetString("btn_RandomizeLoadout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ammo:.
        /// </summary>
        public static string lbl_Ammo {
            get {
                return ResourceManager.GetString("lbl_Ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run:.
        /// </summary>
        public static string lbl_ArmorRun {
            get {
                return ResourceManager.GetString("lbl_ArmorRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage:.
        /// </summary>
        public static string lbl_Damage {
            get {
                return ResourceManager.GetString("lbl_Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear Slots:.
        /// </summary>
        public static string lbl_GearSlots {
            get {
                return ResourceManager.GetString("lbl_GearSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head Protection:.
        /// </summary>
        public static string lbl_HeadArmor {
            get {
                return ResourceManager.GetString("lbl_HeadArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health:.
        /// </summary>
        public static string lbl_Health {
            get {
                return ResourceManager.GetString("lbl_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HRV:.
        /// </summary>
        public static string lbl_HRVDuration {
            get {
                return ResourceManager.GetString("lbl_HRVDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recharge:.
        /// </summary>
        public static string lbl_HRVRecharge {
            get {
                return ResourceManager.GetString("lbl_HRVRecharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run:.
        /// </summary>
        public static string lbl_PawnRun {
            get {
                return ResourceManager.GetString("lbl_PawnRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary.
        /// </summary>
        public static string lbl_Primary {
            get {
                return ResourceManager.GetString("lbl_Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range:.
        /// </summary>
        public static string lbl_Range {
            get {
                return ResourceManager.GetString("lbl_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firerate:.
        /// </summary>
        public static string lbl_RateOfFire {
            get {
                return ResourceManager.GetString("lbl_RateOfFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recoil Aim:.
        /// </summary>
        public static string lbl_RecoilAim {
            get {
                return ResourceManager.GetString("lbl_RecoilAim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recoil Hip:.
        /// </summary>
        public static string lbl_RecoilHip {
            get {
                return ResourceManager.GetString("lbl_RecoilHip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload:.
        /// </summary>
        public static string lbl_ReloadEmpty {
            get {
                return ResourceManager.GetString("lbl_ReloadEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload:.
        /// </summary>
        public static string lbl_ReloadPartial {
            get {
                return ResourceManager.GetString("lbl_ReloadPartial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed:.
        /// </summary>
        public static string lbl_Run {
            get {
                return ResourceManager.GetString("lbl_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScopeIn:.
        /// </summary>
        public static string lbl_ScopeInTime {
            get {
                return ResourceManager.GetString("lbl_ScopeInTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aim:.
        /// </summary>
        public static string lbl_SpreadAim {
            get {
                return ResourceManager.GetString("lbl_SpreadAim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hip:.
        /// </summary>
        public static string lbl_SpreadHipfire {
            get {
                return ResourceManager.GetString("lbl_SpreadHipfire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move:.
        /// </summary>
        public static string lbl_SpreadMove {
            get {
                return ResourceManager.GetString("lbl_SpreadMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom:.
        /// </summary>
        public static string lbl_Zoom {
            get {
                return ResourceManager.GetString("lbl_Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdvancedModding.
        /// </summary>
        public static string tbtn_AdvancedModding {
            get {
                return ResourceManager.GetString("tbtn_AdvancedModding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomModules.
        /// </summary>
        public static string tbtn_AllowCustomModules {
            get {
                return ResourceManager.GetString("tbtn_AllowCustomModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debugging.
        /// </summary>
        public static string tbtn_Debugging {
            get {
                return ResourceManager.GetString("tbtn_Debugging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForceRuntimeCheck.
        /// </summary>
        public static string tbtn_ForceRuntimeCheck {
            get {
                return ResourceManager.GetString("tbtn_ForceRuntimeCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RuntimeCheck.
        /// </summary>
        public static string tbtn_RuntimeCheck {
            get {
                return ResourceManager.GetString("tbtn_RuntimeCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server WatchDog.
        /// </summary>
        public static string tbtn_ServerWatchDog {
            get {
                return ResourceManager.GetString("tbtn_ServerWatchDog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateNotice.
        /// </summary>
        public static string tbtn_ShowUpdateNotice {
            get {
                return ResourceManager.GetString("tbtn_ShowUpdateNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StrictModuleChecks.
        /// </summary>
        public static string tbtn_StrictModuleChecks {
            get {
                return ResourceManager.GetString("tbtn_StrictModuleChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows for Weapon Builds which are normaly not possible.
        /// </summary>
        public static string tbtn_TT_AdvancedModding {
            get {
                return ResourceManager.GetString("tbtn_TT_AdvancedModding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows BLREdit to Adopt Modules in the Module Folder into the Installed Module List Client and Server are both set as Default to be Loaded.
        /// </summary>
        public static string tbtn_TT_AllowCustomModules {
            get {
                return ResourceManager.GetString("tbtn_TT_AllowCustomModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doesn&apos;t have any effect currently.
        /// </summary>
        public static string tbtn_TT_Debugging {
            get {
                return ResourceManager.GetString("tbtn_TT_Debugging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forces the Runtime Check Dialog to display.
        /// </summary>
        public static string tbtn_TT_ForceRuntimeCheck {
            get {
                return ResourceManager.GetString("tbtn_TT_ForceRuntimeCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks if all necessary MVC++ Runtimes are installed to make the Gamework only needed when the game was not installed via Steam.
        /// </summary>
        public static string tbtn_TT_RuntimeCheck {
            get {
                return ResourceManager.GetString("tbtn_TT_RuntimeCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables the Server WatchDog which will Restart&apos;s the server instantly if it crashes or get&apos;s closed.
        /// </summary>
        public static string tbtn_TT_ServerWatchDog {
            get {
                return ResourceManager.GetString("tbtn_TT_ServerWatchDog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the default Web browser to the Newest release when a new one is available.
        /// </summary>
        public static string tbtn_TT_ShowUpdateNotice {
            get {
                return ResourceManager.GetString("tbtn_TT_ShowUpdateNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Allows Proxy Modules from the GitHub List.
        /// </summary>
        public static string tbtn_TT_StrictModuleChecks {
            get {
                return ResourceManager.GetString("tbtn_TT_StrictModuleChecks", resourceCulture);
            }
        }
    }
}
