# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    env:
      Solution_Name: BLREdit.sln                        # Replace with your solution name, i.e. MyWpfApp.sln.
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2
        
      - name: Restore NuGet
        run: msbuild $env:Solution_Name /t:Restore /p:Configuration=Release /p:DeployOnBuild=true
        
      - name: Build App
        run: msbuild $env:Solution_Name /p:Configuration=Release /p:DeployOnBuild=true

      - name: Package App
        run: BLREdit\bin\Release\net48\BLREdit.exe -packageSilent

      - name: Upload Logs Artifact
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: BLREdit\bin\Release\net48\logs
        
      - name: Upload BLREdit Artifact
        uses: actions/upload-artifact@v2
        with:
          name: BLREdit
          path: BLREdit\bin\Release\net48\packaged\BLREdit.exe
        
      - name: Upload Assets Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Asstes
          path: BLREdit\bin\Release\net48\packaged\Assets

      - name: Upload DLLs Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dlls
          path: BLREdit\bin\Release\net48\packaged\dlls

      - name: Upload JSON Artifact
        uses: actions/upload-artifact@v2
        with:
          name: json
          path: BLREdit\bin\Release\net48\packaged\json

      - name: Upload Icons Artifact
        uses: actions/upload-artifact@v2
        with:
          name: textures
          path: BLREdit\bin\Release\net48\packaged\textures

      - name: Upload Scopes Artifact
        uses: actions/upload-artifact@v2
        with:
          name: crosshairs
          path: BLREdit\bin\Release\net48\packaged\crosshairs

      - name: Upload Patches Artifact
        uses: actions/upload-artifact@v2
        with:
          name: patches
          path: BLREdit\bin\Release\net48\packaged\patches
