# This is a basic workflow to help you get started with Actions

name: TestBuild

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    env:
      Solution_Name: BLREdit.sln                        # Replace with your solution name, i.e. MyWpfApp.sln.
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2
        
#      - name: Setup NuGet
#        uses: NuGet/setup-nuget@v1.0.2
        
#      - name: Restore NuGet Packages
#        run: nuget restore $env:Solution_Name
        
      - name: Build App
        run: msbuild $env:Solution_Name /t:Restore /p:Configuration=Release /p:DeployOnBuild=true
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: release_build
          path: bin\Release\net48
