# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the release and beta branch
  push:
    branches: [ release, beta ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    env:
      Solution_Name: BLREdit.sln                        # Replace with your solution name, i.e. MyWpfApp.sln.
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Get Next Semver Release Branch
        id: semver-release
        uses: ietf-tools/semver-action@v1
        if: contains(github.ref, 'release')
        with:
          token: ${{ github.token }}
          patchAll: true
          noVersionBumpBehavior: patch
          branch: release

      - name: Get Next Semver Beta Branch
        id: semver-beta
        uses: ietf-tools/semver-action@v1
        if: contains(github.ref, 'beta')
        with:
          token: ${{ github.token }}
          patchAll: true
          noVersionBumpBehavior: patch
          branch: beta

      - name: Print Semver Release Branch
        if: contains(github.ref, 'release')
        run: echo ${{ steps.semver-release.outputs.next }}

      - name: Print Semver Beta Branch
        if: contains(github.ref, 'beta')
        run: echo ${{ steps.semver-beta.outputs.next }}
        
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2
        
      - name: Restore NuGet
        run: msbuild $env:Solution_Name /t:Restore /p:Configuration=Release /p:DeployOnBuild=true
        
      - name: Build App
        run: msbuild $env:Solution_Name /p:Configuration=Release /p:DeployOnBuild=true

      - name: Package App
        run: BLREdit\bin\Release\net48\BLREdit.exe -packageSilent

      - name: Upload Logs Artifact
        uses: actions/upload-artifact@v4
        with:
          name: log
          path: BLREdit\bin\Release\net48\logs

      - name: Publish Release
        uses: softprops/action-gh-release@v2.2.1
        if: contains(github.ref, 'release')
        with:
          generate_release_notes: true
          draft: true
          prerelease: false
          tag_name: ${{ steps.semver-release.outputs.next }}
          files: |
            BLREdit\bin\Release\net48\packaged\BLREdit.zip
            BLREdit\bin\Release\net48\packaged\Assets.zip
            BLREdit\bin\Release\net48\packaged\crosshairs.zip
            BLREdit\bin\Release\net48\packaged\dlls.zip
            BLREdit\bin\Release\net48\packaged\json.zip
            BLREdit\bin\Release\net48\packaged\patches.zip
            BLREdit\bin\Release\net48\packaged\textures.zip            
          
      - name: Publish Beta
        uses: softprops/action-gh-release@v2.2.1
        if: contains(github.ref, 'beta')
        with:
          generate_release_notes: true
          draft: true
          prerelease: true
          tag_name: ${{ steps.semver-beta.outputs.next }}
          files: |
            BLREdit\bin\Release\net48\packaged\BLREdit.zip
            BLREdit\bin\Release\net48\packaged\Assets.zip
            BLREdit\bin\Release\net48\packaged\crosshairs.zip
            BLREdit\bin\Release\net48\packaged\dlls.zip
            BLREdit\bin\Release\net48\packaged\json.zip
            BLREdit\bin\Release\net48\packaged\patches.zip
            BLREdit\bin\Release\net48\packaged\textures.zip       
