# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    env:
      Solution_Name: BLREdit.sln                        # Replace with your solution name, i.e. MyWpfApp.sln.
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Get Semver
        id: semver
        run: echo "VERSION=$(cat BLREdit\semver.txt)" >> "$GITHUB_OUTPUT"

      - name: Print semver
        env:
          VERSION: ${{  steps.semver.outputs.VERSION }}
        run: echo $VERSION